### ISSUE TITLE
Unable to authenticate to OneDrive via GUI

### ISSUE THREAD

**Issue by jje42** [jstaf/onedriver#210]
I have installed onedrive v2.4.13 on a Fedora 35 machine via COPR as per the README. When trying to connect to my OneDrive via the GUI, I enter my email and see the message "Directing you to your organization's sign in page", but then the following error appears:

Error performing TLS handshake: One of the involved algorithms has insufficient security level.

Any ideas what's causing this or how to fix it?

I also tried authenticating via the command line, and this seems to have worked in that `onedrive --dry-run --monitor` lists files from my OneDrive and says it will download them. I don't want to perform a full sync as my OneDrive has more capacity than my local disk, so downloading everything isn't an option.

Despite `onedrive --dry-run --monitor` listing my files, the mount point I selected still shows "Folder is Empty" in nautilus.

Any help would be appreciated. Thanks.

**Comment by jstaf** [comment]
You installed a different onedrive client. Uninstall `onedrive` and install the `onedriver` package instead from COPR (this package installs a `onedriver` and `onedriver-launcher` command... `onedrive` is a different tool). There is a fix for the TLS issue in the v0.12.0 release. If you're still having issues with the built-in browser, use the `--no-browser` option and you can authenticate via Firefox/Chrome.

If you're curious about the cause of the issue, its this: https://bugzilla.redhat.com/show_bug.cgi?id=2024296

Going to close this since it's fixed in the latest version.

**Comment by jje42** [comment]
Thanks so much! FYI, the GUI still failed with the same error, but the
--no-browser option worked. Thanks for writing/sharing this tool.

**Comment by jstaf** [comment]
Hmmm, going to guess account.live.com isn't the only domain that had issues with the certificate in that case then. Do you know/remember the signin domain your organization uses by any chance (just the url of the page where you authenticate/grant onedriver the ability to read files)? I can look a bit more into it if that's the case (currently I've only whitelisted a single domain).

**Comment by jje42** [comment]
It's https://login.microsoftonline.com
